### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by ShayanBahrainy** [Epihaius/panda3dstudio#13]
the studio runs perfect, but when you import the file to panda3d,it doesn't show any Colors

**Comment by Epihaius** [comment]
Hi!

If you mean the color that you can set in the `Name and color` section of the `Object properties` panel, then you are right, this color is not exported with the model. This is not a bug; the purpose of this "scene color" is merely to make it easier to tell different models apart in Studio itself.
If you want a color that you can export, you will have to apply a material to the model:

* in the `Material` section of the `Materials` panel, choose a material (the default `Material 0001` should do fine) and use a button in the `Apply to objects` group ("Selection" if the model is selected, or "Pick" to choose a particular model);
* in the `Basic properties` section, click the "Flat color" color box to set the color you want.

Now when you export the model and load it up in Panda3D, you should see that color.

Let me know if this solves your problem!

**Comment by ShayanBahrainy** [comment]
Thank you
